name: Gitleaks
description: Run Gitleaks on Push and PR events
branding:
  color: purple
  icon: eye
inputs:
  config-path:
    description: 'Path to config (relative to $GITHUB_WORKSPACE)'
    required: false
    default: '.github/.gitleaks.toml'
  log-opts:
    description: 'Git log options to provide to gitleaks (--log-opts)'
    required: false
    default: ''
  working-directory:
    description: 'Working Directory'
    required: false
    default: '.'
outputs:
  result: # id of output
    description: 'Gitleaks log output'
  exitcode: # id of output
    description: 'Success for failure value from scan'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.config-path }}
    - ${{ inputs.log-opts }}
    - ${{ inputs.working-directory }}
